### ISSUE TITLE
Front-end: Spinning wheel while server is restarting

### ISSUE THREAD

**Issue by munnavhai** [MSF-OCB/nixos_encryption_manager#15]
While the server is restarting, there will be a spinning wheel in front-end. This will be done using javascript.

**Comment by R-VdP** [comment]
This needs to take into account the additional servers as well and wait and get confirmation from all of them.

**Comment by R-VdP** [comment]
@munnavhai this is not done yet, the logic to wait and test that the server actually rebooted, is not there yet.
